### ISSUE TITLE
Add Test-DbaMaxDop

### ISSUE THREAD

**Issue by js0505** [sqlcollaborative/dbachecks#184]
Add Test-DbaMaxDop to tests. Assigning to self.

**Comment by js0505** [comment]
Ooops, meant to have this one done for the release. Fell off radar. Just finished it and will submit PR soon.

**Comment by js0505** [comment]
Question, do we want this at Instance level only or also database level or should there be 2 different tests?

**Comment by TheRockStarDBA** [comment]
It has to be instance level. DB does not have maxdop.

**Comment by ClaudioESSilva** [comment]
@TheRockStarDBA since sql server 2016 you have the option to set the maxdop at database scope configuration. 

@js0505 In my opinion this should be 2 different tests, I can have 2 different values that I want to check. Also, I can change some test value config just for one or another database not all of them.

Are you thinking on rely on the Recommend value or on a fixed value set up on configs?

**Comment by potatoqualitee** [comment]
This was the test that was chosen for the crowdsourced Pester test during the precon :D

**Comment by SQLDBAWithABeard** [comment]
He He

Step one
Decide what you want to test
MaxDop
Step two
No Decide exactly what you want to test :-)

**Comment by SQLDBAWithABeard** [comment]
two tests please @js0505
