### ISSUE TITLE
dbachecks wrapper around Unregister-PSFConfig

### ISSUE THREAD

**Issue by jpomfret** [sqlcollaborative/dbachecks#337]
Should we add a wrapper similar to `Set-DbcConfig` to remove configurations? Perhaps `Remove-DbcConfig`? 

Adding for discussion 😃

**Comment by SQLDBAWithABeard** [comment]
Worth a thought @FriedrichWeinmann ?? I had to remove the config from my registry again with the compreesion rename :-)
Is it an easy thing to do (and document) to enable others to do so ?

**Comment by FriedrichWeinmann** [comment]
The PSFramework command to do that would be:
```
Unregister-PSFConfig -Module dbachecks
```
And yes, you can kill individual settings, it tabcompletes for what it finds.
So yes, easy to do and document. Question is merely whether you want a wrapper function for it or tell users to use it plain.

**Comment by jpomfret** [comment]
Only reason I was suggesting a wrapper was because there is for get and set.

**Comment by michalporeba** [comment]
The benefit of adding the Reset-DbcConfig rather than explaining how to use the Unregister-PSFConfig is that we should be able to unregister, and then execute the configuration.ps1 to ensure we have the default values in place. Also it saves the users of dbachecks from the need to go into the awsomness of PSFramework

**Comment by potatoqualitee** [comment]
Agreeed on Reset-DbcConfig. Was just thinking about the need yesterday!
