### ISSUE TITLE
Page Verify - False Flag on <= 2005 TempDB

### ISSUE THREAD

**Issue by LowlyDBA** [sqlcollaborative/dbachecks#435]
## Issue

The check does not skip over tempdb in 2005, where checksum is available overall but [not able to be set on TempDB](https://technet.microsoft.com/en-us/library/cc966545.aspx), and does not skip over 2000 where it is not available at all. For 2000, [torn page detection](https://technet.microsoft.com/en-us/library/aa337525%28v=sql.90%29.aspx?f=255&MSPPError=-2147217396) should be the best practice option.

*Note: Compatibility level does not affect this option, it is only dictated by the instance version*

### General Troubleshooting steps
- [x] Verified running the latest release of dbachecks? 

Does `(Find-Module dbachecks).Version match (Get-Module dbachecks).Version.ToString()`
Y

- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)

**Comment by michalporeba** [comment]
I've been working on much faster database tests which are not using SMO, this issue presents very interesting challenge for me, especially that I haven't seen a 2000 or even 2005 instance for quite a few years now. I will try to make the newer version work with older versions, but I will need some help testing. 

I don't suppose we have an VMs in VSTS hosting 2000 @SQLDBAWithABeard? ;) 
I don't think it is possible to get a developer edition of anything older than 2012 now, or am I wrong?

**Comment by LowlyDBA** [comment]
Definitely wish I didn't need to make this bug, *sigh*. I'm quite happy to be a guinea pig if you can get something working, though I know those versions are far from priorities.

**Comment by michalporeba** [comment]
what a nice surprise, we still have `sys.sysdatabases` for backwards compatibility. I will be able to use that (I think) to develop version for SQL 2000. I'll have something ready over the weekend.

**Comment by niphlod** [comment]
I can be a guinea pig for 2005, not for 2000, but I don't see why it'd be _that_ hard. 
notes: 
  - page_verify_option is there on >= 2005 sys.databases
  - you need to combine also the compat level. on 80 even on 2005 I'm not sure you can enable checksum
  - if page_verify_option is not there, there's always DATABASEPROPERTYEX

last but not least, I think @potatoqualitee has a 2000 around for quick testing

**Comment by LowlyDBA** [comment]
@niphlod 

> you need to combine also the compat level. on 80 even on 2005 I'm not sure you can enable checksum

I was able to turn it on despite compatibility level 80, as I was working through some old servers. Sort of surprised it worked.

**Comment by wsmelton** [comment]
The `sys` schema itself @michalporeba does not exist in SQL Server 2000.

Overall I think @potatoqualitee should decide whether we want to even try and support 2000 because I don't think we should for this module. We already require PowerShell 4.0, which dbatools goes back to 3.0. So considering this module is for newer "tech" I would draw the line somewhere and not have the same backward support we do with dbatools because this module does not serve the same purpose.

The documentation itself for SQL Server 2000....is only available if you still have the installation media. Microsoft has already removed it from BOL and it was not ( and is not ) migrated to the new docs formatted site.

**Comment by wsmelton** [comment]
Compatibility 80 is another beast to deal with as well because certain DMVs and system views will not work the same either. Most things will but we have bugs in dbatools functions (recall a few issues got submitted) because of this as well.

**Comment by SQLDBAWithABeard** [comment]
I am happy to not support 2000 for everything. Some will work some won’t. That’s ok.

**Comment by michalporeba** [comment]
Thanks, that will be very useful, but implementing it (the way I want) depends now on ability to skip tests from inside the It block, so we can skip rather than fail tests which are not support in the specific version, and that we can unit test that behaviour. I've got a PR with pester already, I'm now waiting for it to hopefully get approved soon but it seems every body is on conferences these days ;)

https://github.com/pester/Pester/pull/1026

**Comment by ashdar** [comment]
Any chance of this moving forward? The above-linked Pester issue was last commented-on in July. 

I run over 31,000 tests (in total) every day. This issue explains 3 of my 17 failures. I would like to get those 3 items out of the list of "I just need to ignore that one" that I keep in my head. 

I can test against 1 development and 2 production SQL 2005 instances, which will be up and running for another 6 to 12 months.
