### ISSUE TITLE
New Command: Reset-DbcConfig

### ISSUE THREAD

**Issue by tootblan** [sqlcollaborative/dbachecks#439]
## Feature Request

I had a need today to completely reset the machine I've been running dbachecks on. The Slack channel guided me towards manually deleting the registry entries, but it looks like PSFramework has a mechanism for doing this already: 

`Unregister-PSFConfig -Module dbachecks`

Should we add a simple wrapper called something like `Reset-DbcConfig` or `Unregister-DbcConfig`? 

Or go futher and write `Uninstall-DbcChecks` which would call `Unregister-PSFConfig` and `Uninstall-Module`? This seems more in line with what's been done already with `Update-DbcChecks`. 

(Thanks to @gbargsley & @michalporeba for their assistance on Slack today.)

**Comment by michalporeba** [comment]
I think uninstalling is a step too far, but the more I think about it, the more I like idea of simply reset of all configuration, or specific config value. 

The benefit of adding the `Reset-DbcConfig` rather than explaining how to use the `Unregister-PSFConfig` is that we should be able to unregister, and then execute the `configuration.ps1` to ensure we have the default values in place. Also it saves the users of dbachecks from the need to go into the awsomness of PSFramework

**Comment by tootblan** [comment]
Turns out @jpomfret had this same idea six weeks ago and opened issue #337. I'm closing my issue and moving the discussion over to #337.
