### ISSUE TITLE
Expecting $NULL but got a Value errors - These seem to be wrong checks

### ISSUE THREAD

**Issue by Ant-Green** [sqlcollaborative/dbachecks#497]
First time running dbachecks so these may be me not understanding the output but they seem like errors

Upon running -AllChecks upon a new build server

Failsafe Operator, is specified but it is wanting a NULL, this should be expecting a value

```
Context Testing failsafe operator exists on <Server>\<Instance>
      [-] failsafe operator on <Server>\<Instance> exists 1.62s
        Expected $null, because The failsafe operator will ensure that any job failures will be notifed to someone if not set explicitly, but got 'SQLLog'.
        52:                     (Connect-DbaInstance -SqlInstance $psitem).JobServer.AlertSystem.FailSafeOperator | Should -Be $failsafeoperator -Because 'The failsafe operator will ensure that any job failures will be notifed to someone if not set explici
tly'
        at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.1.138\checks\Agent.Tests.ps1: line 52
```

DBMail profile, is specified but it is wanting a NULL, this should be expecting a value

```
Context Testing database mail profile is set on <Server>\<Instance>
      [-] database mail profile on <Server>\<Instance> is  1.23s
        Expected $null, because The database mail profile is required to send emails, but got 'SQLLog'.
        65:                     (Connect-DbaInstance -SqlInstance $psitem).JobServer.DatabaseMailProfile | Should -Be $databasemailprofile -Because 'The database mail profile is required to send emails'
        at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.1.138\checks\Agent.Tests.ps1: line 65
```

Active Directory Domain, computer is joined to the domain, but is wanting a NULL, this should be wanting a values

```
Context Testing Active Directory Domain Name on <Server>
      [-] <Server> Should Be on the Domain  448ms
        Expected $null, because The machine needs to be on the domain, but got 'domain.rootdomain.com'.
        8:                 (Get-DbaCmObject -Class Win32_ComputerSystem -ComputerName $psitem -Credential $credential).Domain | Should -Be $domain -Because 'The machine needs to be on the domain'
        at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.1.138\checks\Domain.Tests.ps1: line 8
```

**Comment by SQLDBAWithABeard** [comment]
Hi @AntG1985  

Because those configurations do not have a default value the check will evaluate against a NULL value and fail.

If you run

````powershell
Get-DbcCheck | Out-GridView
````
You can see the configuration items that are required for each check. So the failsafe operator for example requires the config agent.failsafeoperator

![image](https://user-images.githubusercontent.com/6729780/41404139-52e7e95a-6fbe-11e8-87bd-299e98418d74.png)

You can set this with 

Set-DbcConfig -Name agent.failsafeoperator -Value "The OperatorName I require"

and see all of the configured values using

````powershell
Get-DbcConfig | Out-GridView
````

![image](https://user-images.githubusercontent.com/6729780/41404287-b6664288-6fbe-11e8-8a4b-a35051073c6d.png)

I hope that helps to enable you to work out how to configure the other values that you need also. Feel free to join the SQL Community Slack at sqlps.io/slack and ask for help in the #dbachecks channel as well

**Comment by SQLDBAWithABeard** [comment]
Any value that you wish set or change needs to be done with Set-DbcConfig.

Only SqlInstance, ComputerName and SqlCredential can be set at when you call Invoke-DbcCheck

Best Regards

Rob Sewell

Cloud and Datacenter MVP
https://robsewell.info
https://sqldbawithabeard.com
@sqldbawithbeard<https://twitter.com/sqldbawithbeard>
https://uk.linkedin.com/in/robsewellsqldba
mrrobsewell@outlook.com<mailto:mrrobsewell@outlook.com>
