### ISSUE TITLE
Cost threshold for Parallelism

### ISSUE THREAD

**Issue by kevchant** [sqlcollaborative/dbachecks#498]
## Feature Request
   
Check if Cost threshold for parallelism is still set to the default value of 5
   
### What should be configurable for the results of the check ?
    
Alert if it is still the default of five and suggest changing it to higher value and/or investigate workloads 
    
### What should be able to be excluded from being tested ?
    
Single core instances  
   
## Additional information    
    
I might have missed this suggestion elsewhere, if I have then I do apologise. Default value of 5 is fairly low, and was set a very long time ago when hardware was different, investigating workload and changing to higher reduces amount of CPU contention (or test using a value between 25-50 initially).

**Comment by SQLDBAWithABeard** [comment]
We can of course write that check and for people like yourself who have a specific need you can set ti to the value you expect the instance to be at.

But what about default values for the test?

I cant see a way for us to be able to easily identify if it should not be 5 which may not be causing issues or to identify what it should be. A learned colleague performed a search and there are dozens of different "suggested default values" which leads me to think it is not something we can define although happy to let the SME for that particular instance define it?

Would it be acceptable to write the check but by default have it skipped so that if people want to check for a specific value they will have to set a configuration item to enable the check and also set their required value?

**Comment by kevchant** [comment]
Of course, after all it'll be for the benefit of everybody in the cummunity and everybody has different workloads on their SQL instances. I've looked myself in the past, there's not a 'one size fits all', I just suggested those values as a starting point for testing. Just highlight it should be changed and should probably test higher values against their workload (or calculate from their existing workload as guides online how to do it).

**Comment by SQLDBAWithABeard** [comment]
@kevchant  - Apologies It has taken me ages to get back to this -
The instance MaxDop check uses [Test-DbaMaxDop](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Test-DbaMaxDop.ps1) - Does that give you what is required ? (If not please can you raise an issue on dbatools for Test-MaxDop and I will add it in to dbachecks, if not can I close this one?
