### ISSUE TITLE
'Get-DbcCheck' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by francescovista** [sqlcollaborative/dbachecks#543]
### General Troubleshooting steps
execute the command Get-DbcCheck

I receive the error: 

```
Get-DbcCheck : The term 'Get-DbcCheck' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-DbcCheck
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-DbcCheck:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

![error](https://user-images.githubusercontent.com/30395256/45124970-8e0f3a80-b1c0-11e8-87d1-8ca89b7af7ec.PNG)

### Version Information
 - Operating System (Name|Version): Windows 10 Enterprise
 - PowerShell Version: 

```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      15063  1155
```

 - SQL Server (Edition|Version): 

Microsoft SQL Server Management Studio						13.0.16106.4
Microsoft Analysis Services Client Tools						13.0.1700.441
Microsoft Data Access Components (MDAC)						10.0.15063.0
Microsoft MSXML						3.0 4.0 6.0 
Microsoft Internet Explorer						9.11.15063.0
Microsoft .NET Framework						4.0.30319.42000
Operating System						6.3.15063

Yes, modules are all installed and at the latest version:

![modules](https://user-images.githubusercontent.com/30395256/45125059-e5ada600-b1c0-11e8-88a7-b2e6dda03870.PNG)

### Steps to Reproduce
execute the command Get-DbcCheck

**Comment by FriedrichWeinmann** [comment]
Hi @francescovista ,

looks like PowerShell can't find the module!
Just in case, keep in mind that `Get-DbcCheck` is part of `dcotools`, not `dbatools`
Running `Install-Module dcotools` would fix that, if it's plain missing.

Otherwise ensure that the module is in the correct folder and detectable by PowerShell:
```
Get-Module dcotools -ListAvailable
```
If the previous command does not return anything, then PowerShell will not see the module, leading to the error you reported. If that refuses to show, check your local folders for content. Your local antivirus might also interfer with installation sometimes, but that usually is the case when it is locking large binaries, which dcotools does not have (but PSFramework and dbatools both have those, so if these two modules made it onto your system, that is likely not the issue).

Cheers,
Fred

**Comment by francescovista** [comment]
Time to buy a pare of glasses for me.
I taught you mentioned dbatool on your readme.md...

BTW, I cannot install dcotools:

PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'dcotools'.
Try Get-PSRepository to see all available registered module repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.6.7\PSModule.psm1:9491 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Ex
   ception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

![definetly](https://user-images.githubusercontent.com/30395256/45125698-cb28fc00-b1c3-11e8-9097-9c4135c26f9b.PNG)

**Comment by FriedrichWeinmann** [comment]
Damn, I'm a total fool, mixing up modulenames here ^^
Sorry
Not `dcotools` (which is a project I recently concluded) but `dbachecks`

**Comment by SQLDBAWithABeard** [comment]
I see that Fred has sorted this - Thanks Fred :-)
