### ISSUE TITLE
Set-DbcConfig Could not update configuration

### ISSUE THREAD

**Issue by blitzd** [sqlcollaborative/dbachecks#621]
I get this error when trying to set some config options, like this:
```
PS C:\PowerShell> Set-DbcConfig -Name skip.diffbackuptest -Value True
WARNING: [13:18:59][Set-PSFConfig] Could not update configuration: dbachecks.skip.diffbackuptest
```
And the immediate value returned shows that the config was not set.

dbachecks=1.1.173
PSFramework=1.0.2
Pester=4.8.1

All tools were installed just today so should be latest stable versions.

**Comment by SQLDBAWithABeard** [comment]
HI @blitzd 

That error is because there is no config called skip.diffbackuptest

You can find the configurations using

````Get-DbcConfig````

and you can get the checks and the config associated with them using

```` Get-DbcCheck````

You can see the code from my demos here https://github.com/SQLDBAWithABeard/Presentations/blob/master/2019/dbachecks/02%20-Demo.ps1

I think that you are wanting to exclude the differential backups.

You can exclude any check or group of checks by adding it to the command.invokedbccheck.excludecheck configuration with 

````Set-DbcConfig -Name command.invokedbccheck.excludecheck -Value Backup -Append````

for example

**Comment by blitzd** [comment]
Hi Rob,

This is the relevant output of `Get-DbcConfig`:

```

**Comment by SQLDBAWithABeard** [comment]
Apologies, Beard in rushing back from work and not checking properly

You need a $true for that

````Set-DbcConfig -Name skip.diffbackuptest -Value $true````

![image](https://user-images.githubusercontent.com/6729780/58584108-6f206f00-824d-11e9-81c0-7754d4a22b33.png)
