### ISSUE TITLE
Write Invoke-DbcCISChecks which will set any required configuration using Set-DbcConfig and then run checks and save with relevant naming convention.

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbachecks#681]
Write Invoke-DbcCISChecks which will set any required configuration using Set-DbcConfig and then run checks and save with relevant naming convention.

**Comment by ClaudioESSilva** [comment]
Thinking out loud and writing here that maybe we should use the, `-Temporary` parameter here when setting the values for CIS Checks.
This way we will not override other different values used by default for other occasions.

**Comment by SQLDBAWithABeard** [comment]
I am happy for a temporary parameter.
Education for the use of config files using export and Import-DbcConfig in the help is also required to avoid any risk of losing settings

**Comment by tboggiano** [comment]
So we had another ticket to create this function Set-DbcCisConfig to set CIS values which I just stuck in PR for.  So are you guys thinking we could use the Invoke with a Temporary flag, if it has a Temporary flag we export the config file, run Set-DbcCisConfig, then run the tests, then import the config file back.  We are only 4 tickets away from finishing this project, then I can talk Rob into opening one for STIG/DISA.

**Comment by SQLDBAWithABeard** [comment]
I think that works :-)

THANK YOU for all that you do

**Comment by tboggiano** [comment]
@SQLDBAWithABeard the more I look at this one, I think we should just blog about how to run CIS checks using the regular Invoke-DbcCheck and how save your config before you run it.  I know if it like my shop even the Set- command may need tweaked after it is ran because we don't adhere to every standard and would want to pull some out of the tests.  So I'm thinking we don't need this because people can use Invoke-DbcCheck -Tag CIS, use the Set- to set all the skips and values, and then individual sets for anything their company doesn't care about.  But do an export of the config and before and after, and it would custom to the environment, so thus a blog post maybe in leiu of this ticket.  I could be wrong but just thinking of how I would be using it.

**Comment by SQLDBAWithABeard** [comment]
I think I agree. With the Set-DbcCISConfig command I dont think this is needed
